server:
  port: 2222

spring:
  application:
    name: esg-analysis

management:
  endpoints:
    web:
      base-path: "/api/analysis/management"
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
