server:
  port: 1111

spring:
  application:
    name: esg-gateway
  cloud:
    gateway:
      routes:
        - id: gateway-service
          uri: http://localhost:${server.port}
          predicates:
            - Path=/gateway/**
          filters:
              - PrefixPath=/api
        - id: companies-get
          uri: http://localhost:2222
          predicates:
            - Path=/companies/**
          filters:
              - PrefixPath=/api/v1
        - id: companies-post
          uri: http://localhost:2222
          predicates:
            - Path=/companies
            - Method=POST
          filters:
              - PrefixPath=/api/v1
        - id: analysis-service
          uri: http://localhost:2222
          predicates:
            - Path=/analysis/**
          filters:
              - PrefixPath=/api

management:
  endpoints:
    web:
      base-path: "/api/gateway/management"
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always